ENV = "dev"

# Mysql variables
MYSQL_STORAGE = 10
MYSQL_ENGINE_VERSION = "5.7"
MYSQL_INSTANCE_TYPE = "db.t3.micro"

# DOCDB variables
DOCDB_INSTANCE_COUNT = 1
DOCDB_INSTANCE_TYPE = "db.t3.small"
DOCDB_INSTANCE_PORT = 27017

# Redis variables
REDIS_ENGINE_VERSION = "6.x"
REDIS_INSTANCE_TYPE = "cache.t3.small"
REDIS_PORT = 6379
REDIS_INSTANCE_COUNT = 1